# Generated by Django 3.2.7 on 2023-02-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo4',
        ),
    ]
